### ISSUE TITLE
Ledger ETH LP "asset missmatch found"

### ISSUE THREAD

**Issue by jeffdgr8** [asgardex/asgardex-desktop#120] opened 2023-12-15 19:10 UTC
## Prerequisites

ETH/RUNE LP position with Ledger wallet addresses

## Expected Behavior

After selecting both Ledger addresses, allow selecting "add" to add to existing LP position.

## Current Behavior

After selecting both Ledger addresses, the "add" button is disabled with error "asset missmatch found" displayed. ("Missmatch" is also misspelled and should be "mismatch").

## Steps to Reproduce

1. Go to manage ETH LP
2. Initially Ledger addresses are unselected and "no balances" error is shown (would be nice if default could be changed to Ledger addresses or at least remember last selected)
3. If you select RUNE Ledger address first "asset mismatch found" error is correctly shown. If you select ETH Ledger address first "asset mismatch found" error is NOT shown, which is incorrect.
5. Select the other asset's Ledger address and "asset mismatch found" error is (still) displayed. "More information" shows the same two Ledger addresses you are trying to add to the position for.

## Possible Solution

It seems the keystore and Ledger RUNE or ETH addresses used in the logic to display the "asset mismatch found" error and disable the "add" button are somehow being swapped, but only for that logic, address balances are displayed correctly.

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: V1.20.9

- Operating system and version: Windows 11

## Your Environment - Development Version (skip if not using a development version)

- Node version:

- Yarn version:

- Branch:

- Operating system and version:

**Comment by Thorian1te** [comment] 2023-12-18 08:27
thank will look into this issue

**Comment by Thorian1te** [comment] 2024-01-24 03:22
cannot reproduce the error in 1.21.0 

I tried your steps and it appears to be working as designed 

Asset mismatch is correctly displayed when selecting eitther rune or asset ledger address, and when both are selected you can add your amount and the (ADD) button is enabled. If this is no longer an issue this can  be closed

**Comment by jeffdgr8** [comment] 2024-01-24 06:51
@Thorian1te I just tested again with 1.21.0 and this is still an issue.

https://github.com/asgardex/asgardex-desktop/assets/2053817/b1e89089-7642-4e11-ab75-a4370d65ce91

**Comment by Thorian1te** [comment] 2024-01-24 07:11
can I get you to describe to me accurately your address position 
i.e. 
ledgrEth - paired lp - ledgerRune
keystoreEth - paired lp - keystoreRune

I need to know if it's behaving incorrectly. I am assuming you don't want to dox your addresses/lp positions?

**Comment by jeffdgr8** [comment] 2024-01-24 08:19
My LP position is from Ledger ETH and Ledger Rune. I don't have any positions with any of the keystore addresses. You can see asgardex correctly detects the LP position on the right when selecting both Ledger addresses, displaying "Your Pool Share". When selecting any other combination of addresses, it shows "You don't have shares in this pool".

**Comment by Thorian1te** [comment] 2024-04-23 23:38
hey, have you used the latest version & are you still having this issue

**Comment by jeffdgr8** [comment] 2024-04-25 16:05
Yes, I still see the same behavior in 1.21.6. I tested with DOGE and BNB and get the same buggy behavior as ETH with those assets as well. BTC works correctly though.

**Comment by GrassRootsCrypto** [comment] 2024-06-18 02:14
> Yes, I still see the same behavior in 1.21.6. I tested with DOGE and BNB and get the same buggy behavior as ETH with those assets as well. BTC works correctly though.

Please retest with 1.21.9 when it is released and let me know.

**Comment by jeffdgr8** [comment] 2024-06-25 22:53
After updating to 1.21.9 I get the error:

> ERROR TRYING TO IMPORT LEDGER ACCOUNTS
INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/0: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/1: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/2: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/3: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/4: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER CAN'T DECODE CHAIN FROM BNB INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/5: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/6: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER INVALID VALUE UNDEFINED SUPPLIED TO : ARRAY<{ KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }>/7: { KEYSTOREID: NUMBER, ADDRESS: STRING, CHAIN: CHAINIO, NETWORK: NETWORKIO, WALLETACCOUNT: NUMBER, WALLETINDEX: NUMBER, HDMODE: HDMODE }/WALLETACCOUNT: NUMBER

**Comment by Thorian1te** [comment] 2024-09-13 04:59
I found the issue, it will be fixed in the next release. Btw that is just a once off error. import your ledger addresses again. it was because we added account to the storage structure

**Closed as completed** 2024-09-16 00:00 UTC
Labels: bug

**Comment by jeffdgr8** [comment] 2024-10-25 19:26
@Thorian1te I just tested with 1.22.7 and found DOGE and BNB are fixed, however ETH is still broken. The LP share and wallet balances show correctly, but it still says "asset mismatch found" and the add button is disabled.

**Comment by Thorian1te** [comment] 2024-10-27 23:47
make sure that if it was a ledger position then the correct ledger box is ticked.

**Comment by jeffdgr8** [comment] 2024-10-28 16:47
I'm confident the correct Ledger boxes are ticked. Both sides of the LP are Ledger addresses. The behavior remains the same as the video I posted previously for ETH. DOGE and BNB now work correctly.
