### ISSUE TITLE
Clicked UPGRADE on RUNE in Asgardex and RUNE got swallowed ?

### ISSUE THREAD

**Issue by AncientSion** [asgardex/asgardex-desktop#91] opened 2023-11-11 18:43 UTC
Some minutes ago i tried upgrading some old RUNE that i had held in Asgardex for a long while. Asgardex did give me the option to Upgrade them, so i did that. However, now the RUNE are gone, the TX in the inspectors says

WarningTransfer refunded: TxType not supported: switch

However, Asgardex in principal allowed me to send the TX using the upgrade button.
I believe i was using V 1.12 at the time.

Did i lose my unupgraded RUNE entirely ?

**Comment by paju1986** [comment] 2023-11-11 18:47
as far as i know the ERC20 rune kill switch was reached some time ago...

**Comment by Thorian1te** [comment] 2023-11-14 13:16
we are currently at v1.20.6. The feature to upgrade was remove many versions ago and so was the last day to upgrade your rune via asgardex. You may be able to still upgrade at uni swap. 
the app notifies you to update your version at the top bar, pls heed to this otherwise you'll run into know bugs.

**Comment by Thorian1te** [comment] 2023-11-14 13:17
closing this as no further help can be given & its not a bug.

**Closed by Thorian1te** 2023-11-14 13:17 UTC
