### ISSUE TITLE
Not able to deposit ATOM intp savers

### ISSUE THREAD

**Issue by erikd** [asgardex/asgardex-desktop#424] opened 2024-10-16 05:47 UTC
## Prerequisites

Asgardex with ATOM

## Expected Behavior

Expect deposits to savers to work

## Current Behavior

Fails to deposit.

## Steps to Reproduce

1. Have ATOM in Asgardex
2. Go to wallets page and locate ATOM
3. Press the "Earn" button for ATOM
4. Enter an amount to deposit (leaving a balance of 6 ATOM)
5. Enter wallet password and then press confirm

I thought that would be sufficient, but nothing happens.

I tried to do the same on THORSwap and that also failed :shrug: .

## Your Environment - Release Version (skip if not using a release version)

- ASGARDEX desktop version: 1.22.6 from debian package on GH
- Operating system and version: Debian Testing

**Comment by Thorian1te** [comment] 2024-10-16 22:52
Asgardex is having an issue with adding savers - this is a thornode issue which should be fixed in the next release. 

Info:
Issue https://discord.com/channels/838986635756044328/1290719412672004146/1290722424756768899
THORNode Fix https://gitlab.com/thorchain/thornode/-/merge_requests/3764 in v2.137.0
We don't know when thornode v2.137.0 will be released. It should return to normal once the next version is released.

**Comment by GrassRootsCrypto** [comment] 2024-10-23 21:29
Duplicate of #416

**Closed as completed** 2024-10-23 23:46 UTC
Labels: bug
